# The docker-compose.override.yml file is automatically interpreted by docker-compose program along with docker-compose.yml
#
# The docker-compose.override.yml file is NOT interpreted if you specify the docker-compose file explicitly with -f flag like
# docker-compose up -f docker-compose.yml --> docker-compose.override.yml is NOT going to be processed.
#
# override file used on developer workstations to bind volumes for direct code modifications.
version: '3.8'
services:
  # react application
  todo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app

  # FastApi application
  todo-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/code

  # reverse proxy for frontend/backend (fixes problems with CORS and simpler to deploy)
  todo-reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile

  # fake smtp server to intercept and view sent emails
  # todo-mailhog:
  #   ~


  # todo-worker:
  #   ~

  # todo-redis:
  #   ~

  todo-flower:
    image: mher/flower:0.9.4